// ===== WORD BANK FEATURE — word meanings (shared dictionary) =====
// A flat word -> definition lookup used by Level 1's "Hear in a sentence".
// This is a dictionary, NOT a word list — meanings are the same regardless of
// category, so sharing it does not mix Category 1 and Category 4 word sets.
//
// To add a meaning, add a "Word": "definition" entry (any category, any letter).

export const WORD_MEANINGS: Record<string, string> = {
  "Ape": "A large animal like a monkey but with no tail",
  "Arm": "The part of your body from your shoulder to your hand",
  "Ash": "The grey powder left after something burns",
  "Able": "Having the skill or power to do something",
  "Acre": "A unit for measuring land area",
  "Area": "A part or section of a place",
  "Axle": "A rod that connects two wheels together",
  "Admit": "To say that something is true",
  "Adult": "A fully grown person",
  "Ahead": "In front of or further forward",
  "Alarm": "A warning sound or signal",
  "Album": "A book for photos or a collection of songs",
  "Alert": "Quick to notice things; watchful",
  "Amaze": "To surprise someone greatly",
  "Among": "In the middle of a group of things",
  "Ample": "More than enough",
  "Amuse": "To make someone laugh or smile",
  "Angel": "A kind and heavenly being",
  "Angry": "Feeling very upset or cross",
  "Annoy": "To bother or irritate someone",
  "Apple": "A round fruit that can be red or green",
  "Apron": "A cover worn over clothes to keep them clean",
  "Arrow": "A pointed stick shot from a bow",
  "Atlas": "A book of maps",
  "Avoid": "To stay away from something",
  "Award": "A prize given for doing something well",
  "Bee": "A flying insect that makes honey",
  "Box": "A container with four sides",
  "Bud": "A small flower that has not opened yet",
  "Bye": "A word said when leaving someone",
  "Baby": "A very young child",
  "Back": "The rear part of something",
  "Balm": "A cream that soothes pain",
  "Bath": "A large container filled with water for washing",
  "Bead": "A small round ball used in jewellery",
  "Bear": "A large furry wild animal",
  "Belt": "A strap worn around the waist",
  "Bend": "To curve or turn something",
  "Bird": "An animal with wings and feathers",
  "Blew": "Past tense of blow — the wind blew",
  "Boat": "A vehicle that travels on water",
  "Boil": "To heat water until it bubbles",
  "Bone": "The hard part inside your body",
  "Bore": "To make someone feel uninterested",
  "Born": "To come into the world",
  "Bowl": "A round deep dish for food",
  "Buck": "A male deer",
  "Bulb": "The glass part of a light that glows",
  "Bull": "A male cow",
  "Bump": "A small raised lump",
  "Busy": "Having lots of things to do",
  "Badge": "A small sign worn to show who you are",
  "Basin": "A round bowl used for washing",
  "Begin": "To start something",
  "Below": "At a lower level or position",
  "Bench": "A long seat for more than one person",
  "Berry": "A small juicy fruit",
  "Blade": "The sharp cutting edge of a knife",
  "Blaze": "A bright fire or flame",
  "Bless": "To wish someone good things",
  "Blind": "Unable to see",
  "Blood": "The red liquid that flows inside your body",
  "Bloom": "When a flower opens up",
  "Blush": "When your face turns red from embarrassment",
  "Board": "A flat piece of wood",
  "Boast": "To brag about yourself",
  "Boost": "To increase or improve something",
  "Brain": "The organ in your head used for thinking",
  "Brave": "Not afraid of danger",
  "Bread": "A baked food made from flour",
  "Brick": "A block used to build walls",
  "Brook": "A small stream of water",
  "Brown": "A colour like chocolate",
  "Brush": "A tool with bristles for painting or cleaning",
  "Bugle": "A small trumpet instrument",
  "Bunch": "A group of things together",
  "Bakery": "A place where bread and cakes are made",
  "Bangle": "A bracelet worn on the wrist",
  "Banker": "A person who works at a bank",
  "Barley": "A grain used to make food and drinks",
  "Barrel": "A large round container",
  "Basket": "A container made of woven material",
  "Battle": "A fight between two groups",
  "Beauty": "The quality of being attractive",
  "Before": "Earlier than something else",
  "Behind": "At the back of something",
  "Beyond": "Further away than something",
  "Borrow": "To use something that belongs to someone else",
  "Bought": "Past tense of buy — she bought a book",
  "Bounce": "To spring up after hitting something",
  "Branch": "A part of a tree that grows from the trunk",
  "Broken": "Something that is damaged and not working",
  "Bullet": "A small metal object fired from a gun",
  "Butter": "A yellow food made from cream",
  "Bandage": "A strip of cloth used to cover a wound",
  "Bicycle": "A two-wheeled vehicle you pedal",
  "Blanket": "A thick cover used to keep warm",
  "Brother": "A boy who has the same parents as you",
  "Baseball": "A sport played with a bat and ball",
  "Baseline": "The starting line in a game or chart",
  "Birthday": "The day you were born",
  "Breakfast": "The first meal of the day",
  "Basketball": "A sport where you throw a ball into a hoop",
  "Cab": "A taxi car",
  "Cop": "A police officer",
  "Cage": "A box with bars for keeping animals",
  "Cake": "A sweet baked food for celebrations",
  "Cane": "A thin stick used for walking",
  "Cash": "Money in coins or notes",
  "Chat": "A friendly conversation",
  "Chef": "A person who cooks in a restaurant",
  "Chop": "To cut something into pieces",
  "City": "A large town with many people",
  "Claw": "The sharp nail of an animal",
  "Clay": "A soft earth used to make pots",
  "Club": "A group of people with the same interest",
  "Clue": "A hint that helps solve a mystery",
  "Coin": "A round piece of metal money",
  "Comb": "A tool with teeth used to tidy hair",
  "Corn": "A yellow vegetable that grows on a cob",
  "Crab": "A sea creature with claws and a hard shell",
  "Cube": "A 3D shape with six equal square sides",
  "Cure": "A treatment that makes an illness go away",
  "Curl": "A curved or spiral shape",
  "Chain": "A series of metal rings linked together",
  "Chase": "To run after someone",
  "Check": "To look at something carefully",
  "Chest": "The front part of your body or a storage box",
  "Chine": "A cut of meat from the backbone",
  "Choir": "A group of people who sing together",
  "Clean": "Free from dirt",
  "Cliff": "A steep rocky face by the sea",
  "Clock": "A device that shows the time",
  "Coach": "A person who trains others",
  "Count": "To say numbers in order",
  "Court": "A place where games or legal cases happen",
  "Crack": "A thin break in something",
  "Craft": "A skill made with your hands",
  "Crawl": "To move on your hands and knees",
  "Creep": "To move very slowly and quietly",
  "Crown": "A ring worn on a king or queen's head",
  "Cruel": "Causing pain on purpose",
  "Curve": "A smooth bent line",
  "Camera": "A device used to take photos",
  "Candle": "A wax stick that gives light when burned",
  "Casket": "A small box for jewellery or a coffin",
  "Castle": "A large stone building with towers",
  "Caught": "Past tense of catch",
  "Cellar": "A room under a building",
  "Change": "To become different",
  "Church": "A building where Christians worship",
  "Circus": "A show with clowns and acrobats",
  "Clever": "Quick to learn and understand things",
  "Clumsy": "Often dropping or bumping into things",
  "Due": "Expected to arrive or happen",
  "Dye": "A coloured liquid used to change colour",
  "Damp": "Slightly wet",
  "Dark": "Without light",
  "Dawn": "The beginning of the day when the sun rises",
  "Deaf": "Unable to hear",
  "Dear": "Loved very much",
  "Deck": "A flat surface on a ship",
  "Desk": "A table used for writing or working",
  "Dial": "A round control on a device",
  "Dive": "To jump headfirst into water",
  "Dome": "A round roof shaped like half a ball",
  "Dove": "A white bird that is a symbol of peace",
  "Down": "From a higher to a lower place",
  "Drag": "To pull something along the ground",
  "Drum": "A musical instrument you hit",
  "Dusk": "The time just before it gets dark",
  "Duty": "Something you are responsible for doing",
  "Daddy": "An informal word for father",
  "Daily": "Happening every day",
  "Dance": "To move your body to music",
  "Doubt": "Not being sure about something",
  "Dozen": "A group of twelve",
  "Drama": "An exciting or emotional situation or play",
  "Dream": "Images and thoughts in your mind while sleeping",
  "Drink": "To swallow a liquid",
  "Drive": "To control a vehicle",
  "Drown": "To die in water because you cannot breathe",
  "Dwell": "To live in a place",
  "Daring": "Willing to do brave things",
  "Decide": "To make a choice",
  "Delete": "To remove something",
  "Desert": "A very dry area with little water",
  "Device": "A tool or machine made for a purpose",
  "Dinner": "The main meal of the day",
  "Donkey": "An animal like a small horse with long ears",
  "Double": "Twice the amount",
  "Dragon": "An imaginary fire-breathing creature",
  "Drawer": "A sliding box in a piece of furniture",
  "Duster": "A cloth used for cleaning dust",
  "Daughter": "A female child",
  "Each": "Every single one",
  "East": "The direction where the sun rises",
  "Easy": "Not difficult",
  "Echo": "A sound that bounces back to you",
  "Edge": "The border or end of something",
  "Even": "Flat and level",
  "Exit": "The way out of a place",
  "Eagle": "A large bird that hunts for food",
  "Earth": "The planet we live on",
  "Enemy": "Someone who wants to harm you",
  "Entry": "The way into a place",
  "Equal": "The same in size or amount",
  "Every": "Each one without exception",
  "Exact": "Completely correct and precise",
  "Excel": "To do something very well",
  "Extra": "More than what is needed",
  "Edible": "Safe and good to eat",
  "Empire": "A group of countries ruled by one person",
  "Energy": "The power to do things",
  "Escape": "To get away from a place",
  "Entrust": "To give someone responsibility for something",
  "Explain": "To make something clear and easy to understand",
  "Fat": "Having a lot of body weight",
  "Few": "A small number of things",
  "Fog": "Thick mist that makes it hard to see",
  "Fry": "To cook food in hot oil",
  "Fact": "Something that is true",
  "Fame": "Being known by many people",
  "Fast": "Moving quickly",
  "Fees": "Money paid for a service",
  "Felt": "Past tense of feel",
  "Film": "A movie or a thin layer on a surface",
  "Fine": "Very good or a money penalty",
  "Flag": "A coloured cloth that represents a country",
  "Flap": "To wave up and down",
  "Fold": "To bend something over itself",
  "Fort": "A strong building used for defence",
  "Free": "Not costing money or not trapped",
  "Fury": "Very great anger",
  "Fairy": "A tiny magical creature with wings",
  "Faith": "Strong belief in something",
  "False": "Not true",
  "Fancy": "Decorative or to like something",
  "Feast": "A large and special meal",
  "Fetch": "To go and get something",
  "Field": "An open area of land",
  "Final": "The last one",
  "Flame": "The bright part of a fire",
  "Flask": "A small bottle for carrying drinks",
  "Float": "To rest on top of water",
  "Floor": "The surface you walk on",
  "Force": "Power or strength",
  "Frame": "A border around a picture",
  "Fresh": "New and clean",
  "Frock": "A dress",
  "Fabric": "Cloth or material",
  "Famine": "A time when there is not enough food",
  "Father": "A male parent",
  "Fellow": "A man or boy",
  "Figure": "A shape or number",
  "Flight": "Travelling through the air",
  "Follow": "To go behind someone",
  "Forest": "A large area covered with trees",
  "Formal": "Following rules and not casual",
  "Freeze": "To turn into ice from cold",
  "Friend": "Someone you like and trust",
  "Fashion": "A popular style of clothing",
  "Fertile": "Good for growing plants",
  "Forgive": "To stop being angry at someone",
  "Farewell": "A goodbye",
  "Gem": "A precious stone like a diamond",
  "God": "A divine or holy being",
  "Gate": "A door in a fence or wall",
  "Gift": "A present given to someone",
  "Girl": "A female child",
  "Glad": "Feeling happy",
  "Glow": "A soft steady light",
  "Glue": "A sticky substance used to join things",
  "Goat": "An animal with horns that gives milk",
  "Gown": "A long dress",
  "Grin": "A big smile",
  "Grow": "To get bigger",
  "Giant": "Something very large",
  "Globe": "A round model of the Earth",
  "Gloom": "Darkness or sadness",
  "Glory": "Great fame and honour",
  "Grade": "A level or mark given for work",
  "Grain": "A seed of wheat or rice",
  "Grass": "The green plant that covers lawns",
  "Group": "A number of people or things together",
  "Guard": "To watch over and protect something",
  "Guess": "To give an answer without being sure",
  "Galaxy": "A huge group of stars in space",
  "Garden": "An area where plants and flowers grow",
  "Gentle": "Soft and kind",
  "Greedy": "Wanting more than you need",
  "Guilty": "Having done something wrong",
  "Guitar": "A musical instrument with strings",
  "Goodbye": "What you say when leaving someone",
  "Hay": "Dried grass fed to animals",
  "Half": "One of two equal parts",
  "Hall": "A long passage inside a building",
  "Hard": "Not soft or very difficult",
  "Hark": "Listen carefully",
  "Heat": "Warmth from fire or sun",
  "Herb": "A plant used in cooking",
  "Hero": "A person admired for bravery",
  "Hide": "To put yourself where others cannot find you",
  "High": "Far above the ground",
  "Hold": "To keep something in your hand",
  "Habit": "Something you do regularly without thinking",
  "Happy": "Feeling joy and pleasure",
  "Heart": "The organ that pumps blood around your body",
  "Hello": "A greeting when you meet someone",
  "Honey": "A sweet food made by bees",
  "Hotel": "A building where people pay to sleep",
  "Human": "A person",
  "Hurry": "To move or do something quickly",
  "Hammer": "A tool used to hit nails",
  "Handle": "The part you hold to carry something",
  "Health": "The condition of your body",
  "Helmet": "A hard hat that protects your head",
  "Honest": "Always telling the truth",
  "Humble": "Not thinking you are better than others",
  "Hungry": "Wanting food",
  "Holiday": "A time away from school or work",
  "Helicopter": "A flying machine with spinning blades",
  "Idle": "Not doing anything",
  "Iron": "A heavy metal or a tool to smooth clothes",
  "Igloo": "A house made of blocks of snow",
  "Infant": "A very young baby",
  "Inkpot": "A small pot that holds ink",
  "Insect": "A small creature with six legs",
  "Invite": "To ask someone to come somewhere",
  "Iceberg": "A huge block of ice floating in the sea",
  "Jaw": "The lower part of your face that helps you chew",
  "Job": "Work that you do to earn money",
  "Joy": "A feeling of great happiness",
  "Jump": "To push yourself off the ground",
  "Jury": "A group of people who decide in a court",
  "Jelly": "A wobbly sweet food",
  "Jewel": "A precious stone",
  "Joint": "A place where two things are joined",
  "Joker": "A person who tells jokes",
  "Juice": "A drink made from fruit",
  "Jacket": "A short coat",
  "Jumble": "A messy mixture of things",
  "Journey": "A long trip from one place to another",
  "Key": "A metal tool used to open locks",
  "Keen": "Very interested and enthusiastic",
  "Kept": "Past tense of keep",
  "Kite": "A toy that flies in the wind on a string",
  "Knit": "To make fabric using needles and wool",
  "Kneel": "To go down on your knees",
  "Knock": "To hit a door to get someone's attention",
  "Karate": "A martial art from Japan",
  "Kennel": "A small shelter for a dog",
  "Kernel": "The seed inside a nut or fruit",
  "Kidnap": "To take someone away by force",
  "Kidney": "An organ in your body that cleans blood",
  "Kitten": "A young cat",
  "Kitchen": "The room where food is cooked",
  "Law": "A rule that everyone must follow",
  "Low": "Not high up",
  "Lack": "To not have enough of something",
  "Lady": "A polite word for a woman",
  "Land": "The solid ground",
  "Lark": "A small singing bird",
  "Lash": "To tie tightly or a part of your eyelid",
  "Late": "After the expected time",
  "Lazy": "Not wanting to work or do anything",
  "Leaf": "The flat green part of a plant",
  "Leen": "To rest against something at an angle",
  "Left": "The opposite side to right",
  "Liar": "A person who does not tell the truth",
  "Life": "The time between being born and dying",
  "Lily": "A beautiful flower",
  "Lock": "A device that keeps a door shut",
  "Loud": "Making a lot of noise",
  "Love": "A strong feeling of care for someone",
  "Label": "A tag with information",
  "Large": "Big in size",
  "Latch": "A small catch that keeps a door closed",
  "Leech": "A worm-like creature that sucks blood",
  "Least": "The smallest amount",
  "Leave": "To go away from a place",
  "Level": "Flat and even",
  "Limit": "The furthest point allowed",
  "Lobby": "An entrance hall of a building",
  "Local": "Belonging to a nearby area",
  "Lofty": "Very high or tall",
  "Lorry": "A large truck for carrying goods",
  "Lotus": "A beautiful flower that grows in water",
  "Lucky": "Having good things happen by chance",
  "Ladder": "Steps you climb to reach high places",
  "Length": "How long something is",
  "Letter": "A written message or a symbol of the alphabet",
  "Linger": "To stay somewhere longer than needed",
  "Little": "Small in size",
  "Lizard": "A small reptile with four legs",
  "Locket": "A small piece of jewellery that opens",
  "Lovely": "Very beautiful or pleasant",
  "Lantern": "A lamp in a case that you can carry",
  "Leopard": "A large spotted wild cat",
  "Luggage": "Bags and suitcases for travelling",
  "Map": "A drawing that shows an area of land",
  "Mix": "To combine things together",
  "Make": "To create or build something",
  "Many": "A large number of things",
  "Mark": "A spot or sign on something",
  "Mask": "A cover worn over the face",
  "Mean": "Unkind or to have a meaning",
  "Melt": "To turn from solid to liquid with heat",
  "Mend": "To fix something that is broken",
  "Milk": "A white drink that comes from cows",
  "Mild": "Not too strong or extreme",
  "Mind": "The part of you that thinks and feels",
  "Moon": "The large round object that orbits Earth",
  "Moth": "An insect like a butterfly that flies at night",
  "Move": "To go from one place to another",
  "Mule": "An animal that is a mix of horse and donkey",
  "Myth": "An old story about gods or heroes",
  "Magic": "Special powers that do impossible things",
  "Mango": "A sweet tropical fruit",
  "March": "To walk in a military way or the third month",
  "Medal": "A disc given as an award",
  "Metal": "A hard shiny material like iron or gold",
  "Money": "Coins and notes used to buy things",
  "Month": "One of the twelve parts of a year",
  "Moral": "Knowing what is right and wrong",
  "Motor": "A machine that makes things move",
  "Mouse": "A small furry animal or computer device",
  "Mouth": "The opening in your face used for eating",
  "Music": "Sounds arranged in a pleasing way",
  "Magnet": "An object that attracts iron and steel",
  "Malady": "An illness or disease",
  "Master": "An expert at something",
  "Member": "Someone who belongs to a group",
  "Method": "A way of doing something",
  "Middle": "The centre point",
  "Mirror": "A glass surface that shows your reflection",
  "Motion": "The act of moving",
  "Muscle": "Body tissue that helps you move",
  "Myself": "Used to refer to yourself",
  "Million": "The number 1,000,000",
  "Mistake": "Something done wrongly",
  "Minister": "A government leader or church leader",
  "Nib": "The pointed tip of a pen",
  "Now": "At this moment",
  "Nail": "A thin metal spike or the hard tip of a finger",
  "Neat": "Tidy and organised",
  "Neck": "The part of your body between your head and shoulders",
  "Need": "Something you must have",
  "Next": "The one immediately after",
  "Note": "A short written message or a musical sound",
  "Noun": "A word that names a person, place or thing",
  "Nerve": "A thread in your body that carries signals",
  "Never": "At no time",
  "Noble": "Having high moral qualities",
  "Noise": "A loud or unpleasant sound",
  "Narrow": "Not wide",
  "Nation": "A country and its people",
  "Nature": "The natural world of plants and animals",
  "Needle": "A thin pointed tool used for sewing",
  "Nibble": "To take small bites of something",
  "Normal": "Usual and expected",
  "Notice": "To see or become aware of something",
  "Neutral": "Not taking sides",
  "Nursery": "A place where young children are cared for",
  "Network": "A system of connected things",
  "Odd": "Strange or not even",
  "Off": "Away from a place or not working",
  "Own": "To have something that belongs to you",
  "Obey": "To do what you are told",
  "Omit": "To leave something out",
  "Once": "One time only",
  "Oral": "Spoken out loud",
  "Oven": "A heated box used for cooking",
  "Over": "Above or finished",
  "Occur": "To happen",
  "Ocean": "A very large area of sea",
  "Often": "Many times",
  "Olive": "A small fruit used in cooking",
  "Order": "A request or an organised arrangement",
  "Owner": "A person who has something",
  "Object": "A thing you can see and touch",
  "Office": "A room or building where people work",
  "Online": "Connected to the internet",
  "Option": "A choice available to you",
  "Origin": "Where something comes from",
  "Output": "What is produced by a machine or person",
  "Operate": "To make a machine work",
  "Paw": "The foot of an animal",
  "Pay": "To give money for something",
  "Ply": "A layer of wood or to travel regularly",
  "Pack": "To put things in a bag",
  "Paid": "Given money for work done",
  "Page": "One side of a sheet of paper in a book",
  "Park": "A public area with grass and trees",
  "Pass": "To go by something",
  "Past": "Time that has already happened",
  "Path": "A way or track to walk on",
  "Pave": "To cover ground with stone or concrete",
  "Peer": "To look closely or someone the same age",
  "Pest": "An insect or animal that causes damage",
  "Pick": "To choose or to pull something off",
  "Pine": "A tree with needles or to feel sad",
  "Plan": "An idea for doing something",
  "Plum": "A small purple fruit",
  "Plus": "Adding or a positive thing",
  "Poet": "A person who writes poems",
  "Poke": "To push with a finger",
  "Pond": "A small area of water",
  "Poor": "Having very little money",
  "Port": "A harbour where ships dock",
  "Paint": "A coloured liquid used to decorate surfaces",
  "Paper": "Thin sheets used for writing",
  "Paste": "A thick sticky mixture",
  "Petal": "The coloured leaf of a flower",
  "Photo": "A picture taken with a camera",
  "Piano": "A large musical keyboard instrument",
  "Pinch": "To squeeze between fingers",
  "Piper": "A person who plays a pipe instrument",
  "Pitch": "A sports field or a musical note level",
  "Place": "A particular area or position",
  "Plant": "A living thing that grows in soil",
  "Point": "A sharp tip or to direct attention",
  "Pouch": "A small bag or pocket",
  "Prawn": "A small seafood creature",
  "Press": "To push firmly",
  "Pride": "Feeling pleased about achievements",
  "Prime": "The most important or best",
  "Print": "To put words or images on paper",
  "Probe": "To investigate carefully",
  "Prose": "Writing that is not poetry",
  "Proud": "Feeling pleased with yourself",
  "Purse": "A small bag for money",
  "Packet": "A small container or package",
  "Palace": "A grand house where royalty lives",
  "Parent": "A mother or father",
  "Pencil": "A tool for writing with a graphite tip",
  "People": "Human beings",
  "Permit": "To allow something",
  "Person": "An individual human being",
  "Picnic": "An outdoor meal",
  "Pierce": "To make a hole in something",
  "Pillar": "A tall column that supports a building",
  "Pillow": "A soft cushion for your head in bed",
  "Please": "To make someone happy",
  "Pledge": "A serious promise",
  "Plenty": "More than enough",
  "Plural": "More than one",
  "Pocket": "A small bag sewn into clothing",
  "Polish": "To make something shine",
  "Polite": "Having good manners",
  "Potato": "A starchy vegetable grown underground",
  "Powder": "A fine dry substance",
  "Prayer": "Words spoken to God",
  "Pretty": "Attractive to look at",
  "Priest": "A religious leader",
  "Proper": "Correct and suitable",
  "Public": "Open to everyone",
  "Purple": "A colour made by mixing red and blue",
  "Picture": "A drawing or photograph",
  "Pitcher": "A large jug for pouring liquids",
  "Package": "A parcel or bundle of things",
  "Parking": "A place to leave a vehicle",
  "Patient": "Able to wait calmly or a person in hospital",
  "Payment": "Money given for something",
  "Plastic": "A light material made from chemicals",
  "Primary": "First or most important",
  "Problem": "A difficult situation",
  "Promise": "A commitment to do something",
  "Pumpkin": "A large orange vegetable",
  "Password": "A secret word to access something",
  "Platform": "A raised surface or a train station area",
  "Quit": "To stop doing something",
  "Quiz": "A set of questions to test knowledge",
  "Quack": "The sound a duck makes",
  "Queen": "A female ruler of a country",
  "Quick": "Moving fast",
  "Quite": "To a certain degree",
  "Question": "Something you ask to get information",
  "Rap": "To knock quickly or a style of music",
  "Raw": "Not cooked",
  "Ray": "A narrow beam of light",
  "Rub": "To move your hand back and forth on something",
  "Rain": "Water drops falling from clouds",
  "Rank": "A position in order",
  "Rare": "Not common or not fully cooked",
  "Rate": "The speed at which something happens",
  "Read": "To look at words and understand them",
  "Real": "Actually existing",
  "Reel": "A cylinder for winding things around",
  "Rely": "To depend on someone",
  "Rent": "Money paid to use something",
  "Rich": "Having a lot of money",
  "Ripe": "Ready to eat",
  "Roar": "A loud deep sound",
  "Rock": "A hard stone or to move back and forth",
  "Roof": "The covering on top of a building",
  "Rose": "A beautiful flower with thorns",
  "Rule": "A law or instruction to follow",
  "Rush": "To hurry",
  "Radio": "A device that receives broadcast sound",
  "Ranch": "A large farm for cattle",
  "Rapid": "Very fast",
  "Refer": "To mention or direct to something",
  "Relax": "To rest and stop worrying",
  "Remit": "To send money or to cancel a punishment",
  "Reply": "An answer to a message",
  "Rhyme": "Words that end with the same sound",
  "Roast": "To cook in an oven",
  "Robot": "A machine that can do human tasks",
  "Royal": "Belonging to a king or queen",
  "Radish": "A small red root vegetable",
  "Raisin": "A dried grape",
  "Reason": "The explanation for why something happens",
  "Recite": "To say something from memory",
  "Relate": "To connect to something",
  "Remind": "To help someone remember",
  "Return": "To come back or give something back",
  "Riddle": "A puzzling question with a clever answer",
  "Rainbow": "An arc of colours in the sky after rain",
  "Reflect": "To show an image or to think deeply",
  "Remember": "To keep something in your mind",
  "Say": "To speak words",
  "See": "To look at something with your eyes",
  "Set": "A group of things or to put in place",
  "Shy": "Nervous around other people",
  "Sum": "The total when numbers are added",
  "Sack": "A large bag",
  "Sand": "Tiny grains found on beaches",
  "Scan": "To look over quickly",
  "Scar": "A mark left after a wound heals",
  "Seat": "Something you sit on",
  "Seek": "To look for something",
  "Self": "Your own person",
  "Size": "How big or small something is",
  "Skin": "The outer covering of your body",
  "Skit": "A short funny performance",
  "Slab": "A thick flat piece of stone",
  "Slay": "To kill",
  "Slim": "Thin",
  "Snow": "White frozen water that falls from clouds",
  "Soak": "To make something very wet",
  "Soup": "A liquid food made by boiling ingredients",
  "Slug": "A slow creature like a snail without a shell",
  "Spot": "A small round mark or a place",
  "Stem": "The stalk of a plant",
  "Sure": "Certain and confident",
  "Sway": "To move slowly from side to side",
  "Swam": "Past tense of swim",
  "Saint": "A very holy and good person",
  "Satin": "A smooth shiny fabric",
  "Scale": "A device for weighing or the skin of a fish",
  "Scare": "To frighten someone",
  "Scarf": "A piece of cloth worn around the neck",
  "Scold": "To tell someone off",
  "Scope": "The range of what something covers",
  "Sense": "The ability to feel or understand",
  "Serve": "To give food or to help someone",
  "Shade": "An area sheltered from the sun",
  "Shave": "To remove hair from the skin",
  "Shawl": "A large piece of cloth worn over shoulders",
  "Sheep": "A woolly farm animal",
  "Sheet": "A large piece of fabric or paper",
  "Shine": "To give out bright light",
  "Shore": "The land at the edge of a sea",
  "Shout": "To speak very loudly",
  "Slate": "A grey stone used for roofs",
  "Slave": "A person forced to work without pay",
  "Slice": "A thin flat piece cut from something",
  "Slide": "A smooth surface to slip down",
  "Slope": "A surface that goes up or down at an angle",
  "Smart": "Clever or well-dressed",
  "Smash": "To break violently",
  "Smell": "To sense through your nose",
  "Smile": "A happy expression on your face",
  "Snake": "A long reptile with no legs",
  "Socks": "Coverings worn on your feet",
  "Solar": "Related to the sun",
  "Solid": "Hard and firm",
  "Sound": "Something you can hear",
  "South": "The direction opposite to north",
  "Space": "The area beyond Earth or room to move",
  "Spark": "A tiny piece of burning material",
  "Spend": "To use money",
  "Spice": "A flavouring added to food",
  "Spine": "The backbone or the back of a book",
  "Split": "To divide into parts",
  "Spoil": "To damage or ruin something",
  "Sport": "A physical activity done for fun",
  "Spray": "To scatter liquid in small drops",
  "Steam": "Hot water vapour",
  "Steep": "Rising or falling sharply",
  "Stick": "A thin piece of wood or to attach",
  "Storm": "Strong wind and heavy rain",
  "Stuff": "Things or materials",
  "Swift": "Very fast",
  "Swing": "To move back and forth",
  "Settle": "To make your home somewhere",
  "Shabby": "Worn out and looking old",
  "Signal": "A sign that gives information",
  "Silent": "Completely quiet",
  "Smooth": "Having no bumps or roughness",
  "Speech": "Words spoken out loud",
  "Splash": "To scatter water noisily",
  "Spring": "The season after winter or to jump",
  "Square": "A shape with four equal sides",
  "Stable": "Not moving or a building for horses",
  "Strain": "To stretch or put pressure on something",
  "Street": "A road in a town",
  "Strict": "Demanding that rules are followed",
  "Strong": "Having great power",
  "Studio": "A room for art, music or filming",
  "Submit": "To hand in or give something",
  "Servant": "A person who works for another",
  "Station": "A place where trains or buses stop",
  "Stomach": "The organ that digests food",
  "Strange": "Unusual or unfamiliar",
  "Student": "A person who is learning",
  "Subject": "A topic of study",
  "Support": "To help or hold up something",
  "Sentence": "A group of words that makes sense",
  "Straight": "Without bends or curves",
  "Subtract": "To take away a number from another",
  "Tie": "A strip of cloth worn around the neck",
  "Toe": "One of the five digits on your foot",
  "Toy": "Something children play with",
  "Try": "To make an effort to do something",
  "Tug": "To pull with force",
  "Talk": "To speak to someone",
  "Tame": "Not wild and easy to handle",
  "Taxi": "A car you pay to take you somewhere",
  "Team": "A group working together",
  "Text": "Written words or a message",
  "Thaw": "To melt from frozen",
  "Tidy": "Neat and in order",
  "Time": "The measurement of seconds, minutes and hours",
  "Tiny": "Very small",
  "Told": "Past tense of tell",
  "Tool": "An instrument used to do a job",
  "Tram": "A vehicle that runs on tracks in a city",
  "Tray": "A flat board for carrying things",
  "Tube": "A hollow cylinder",
  "Turn": "To rotate or change direction",
  "Tusk": "A long pointed tooth of an elephant",
  "Twin": "One of two children born at the same time",
  "Type": "A kind or sort of thing",
  "Telex": "A system for sending written messages",
  "Thick": "Wide or not thin",
  "Thief": "A person who steals",
  "Thumb": "The shortest and widest finger",
  "Tiger": "A large striped wild cat",
  "Tight": "Firmly fixed or fitting closely",
  "Tired": "Needing rest or sleep",
  "Torch": "A portable light",
  "Total": "The complete amount",
  "Tough": "Strong or difficult",
  "Trace": "To follow the path of something",
  "Tribe": "A group of people living together",
  "Truck": "A large vehicle for carrying goods",
  "Truth": "The real facts about something",
  "Tangle": "A messy knot",
  "Temper": "Mood or to make stronger",
  "Tender": "Gentle and kind or soft to touch",
  "Terror": "Extreme fear",
  "Tragic": "Very sad and unfortunate",
  "Travel": "To go from one place to another",
  "Thimble": "A small cap worn on a finger when sewing",
  "Through": "Moving from one side to the other",
  "Tractor": "A farm vehicle with large wheels",
  "Twinkle": "To shine with a small flickering light",
  "Telephone": "A device used to talk to someone far away",
  "Ugly": "Not attractive to look at",
  "Used": "Already been used before",
  "Under": "Below or beneath something",
  "Unity": "Being joined together as one",
  "Upset": "Feeling unhappy or disturbed",
  "Usual": "What normally happens",
  "Utmost": "The greatest possible amount",
  "Uniform": "Clothes worn by all members of a group",
  "Umbrella": "A device that protects you from rain",
  "Van": "A vehicle for carrying goods",
  "View": "What you can see from a place",
  "Visa": "A document allowing you to enter a country",
  "Verb": "A word that shows an action",
  "Valve": "A device that controls flow of liquid",
  "Venue": "A place where an event is held",
  "Video": "Moving pictures recorded on screen",
  "Vital": "Extremely important",
  "Voice": "The sound you make when speaking",
  "Valley": "A low area of land between hills",
  "Verify": "To check something is true",
  "Visual": "Related to seeing",
  "Village": "A small community in the countryside",
  "Why": "For what reason",
  "Want": "To wish for something",
  "Warm": "Having a comfortable heat",
  "Wave": "A movement of the hand or water",
  "Waste": "To use more than needed",
  "Watch": "To look at something or a device showing time",
  "Wheel": "A round object that turns",
  "White": "The lightest colour",
  "Window": "A glass opening in a wall",
  "Winner": "A person who wins",
  "Wedding": "A ceremony where people get married",
  "Xray": "A beam that passes through the body to take images",
  "Xylophone": "A musical instrument with wooden bars you hit",
  "Year": "A period of 365 days",
  "Young": "Not old",
  "Yellow": "A bright colour like the sun",
  "Zip": "A fastener on clothing or to move fast",
  "Zebra": "A black and white striped animal",
  "Aisle": "A passage between rows of seats",
  "Algae": "Simple plants that grow in water",
  "Annul": "To cancel something officially",
  "Ambidextrous": "Able to use both hands equally well",
  "Atone": "To make up for doing something wrong",
  "Awash": "Covered with water",
  "Azure": "A bright blue colour like the sky",
  "Abrade": "To scrape or wear away a surface",
  "Alumni": "Former students of a school",
  "Anoint": "To rub oil on someone in a ceremony",
  "Assert": "To state something confidently",
  "Astute": "Very clever at understanding things",
  "Asylum": "Protection given to someone in danger",
  "Auction": "A sale where things go to the highest bidder",
  "Autism": "A condition that affects how people communicate",
  "Awning": "A canvas shade over a window or door",
  "Abscess": "A painful swelling filled with fluid",
  "Abscond": "To leave secretly to avoid trouble",
  "Abustle": "Busy with activity",
  "Amateur": "A person who does something for fun not money",
  "Anguish": "Severe pain or suffering",
  "Antique": "A very old and valuable object",
  "Appease": "To calm someone by giving them what they want",
  "Applaud": "To clap to show you enjoyed something",
  "Apprise": "To inform or tell someone about something",
  "Ascetic": "Living a very simple life without luxuries",
  "Asinine": "Very stupid or foolish",
  "Assault": "A violent attack on someone",
  "Assuage": "To make an unpleasant feeling less severe",
  "Austere": "Simple and without comfort",
  "Abducted": "Taken away by force",
  "Aberrant": "Different from what is normal",
  "Accurate": "Correct and without errors",
  "Amicable": "Friendly and pleasant",
  "Ancestor": "A family member from long ago",
  "Assembly": "A group gathered together",
  "Audience": "A group watching a performance",
  "Accessory": "An extra item that goes with something",
  "Algorithm": "A set of rules for solving a problem",
  "Ambiguous": "Having more than one possible meaning",
  "Arthritis": "A painful condition affecting joints",
  "Artillery": "Large guns used in warfare",
  "Ascendant": "Rising or becoming more powerful",
  "Attrition": "Gradually wearing something down",
  "Authentic": "Real and genuine",
  "Accomplice": "A person who helps someone do wrong",
  "Assignment": "A task given to someone",
  "Assumption": "Something believed to be true without proof",
  "Auspicious": "Showing signs of future success",
  "Acknowledge": "To accept or admit something is true",
  "Adolescence": "The period of growing from child to adult",
  "Archaeology": "The study of ancient human history",
  "Aristocracy": "The highest class in society",
  "Acquaintance": "A person you know but not well",
  "Advantageous": "Giving a benefit or advantage",
  "Announcement": "A public statement giving information",
  "Administrator": "A person who manages an organisation",
  "Advertisement": "A message promoting a product or service",
  "Borne": "Carried or transported",
  "Bacon": "Smoked or cured meat from a pig",
  "Benign": "Kind and gentle or not harmful",
  "Bicker": "To argue about small unimportant things",
  "Billow": "To swell out like a sail in wind",
  "Broach": "To bring up a subject for discussion",
  "Banquet": "A large formal meal",
  "Barrack": "Buildings where soldiers live",
  "Beastly": "Very unpleasant",
  "Bemused": "Confused and puzzled",
  "Bequest": "Something left to someone in a will",
  "Berserk": "Out of control with anger",
  "Betroth": "To be engaged to marry someone",
  "Bouquet": "A bunch of flowers",
  "Brevity": "Using few words to say something",
  "Bristle": "A short stiff hair",
  "Brocade": "A rich fabric with a raised pattern",
  "Buzzard": "A large bird of prey",
  "Bankrupt": "Unable to pay debts",
  "Barbeque": "Cooking food on a grill outdoors",
  "Biopsy": "Removing tissue from the body for testing",
  "Begotten": "Given birth to",
  "Bequeath": "To leave something to someone in a will",
  "Bewilder": "To confuse someone completely",
  "Biennial": "Happening every two years",
  "Boutique": "A small fashionable shop",
  "Braggart": "A person who boasts a lot",
  "Breakage": "Something that has been broken",
  "Burnette": "A person with dark brown hair",
  "Buoyance": "The ability to float",
  "Barricade": "A barrier to block entry",
  "Battalion": "A large group of soldiers",
  "Becquerel": "A unit measuring radioactivity",
  "Behaviour": "The way a person acts",
  "Bifurcate": "To divide into two branches",
  "Biography": "A book about someone's life",
  "Bountiful": "Large in quantity",
  "Brigadier": "A senior military officer",
  "Brilliance": "Great brightness or intelligence",
  "Broadcast": "To send out information on radio or TV",
  "Brokerage": "A business that buys and sells for others",
  "Brutality": "Extreme cruelty",
  "Beautician": "A person who gives beauty treatments",
  "Beneficial": "Having a good effect",
  "Boisterous": "Noisy and lively",
  "Breathless": "Unable to breathe easily",
  "Beneficiary": "A person who receives a benefit",
  "Cadre": "A small group of trained people",
  "Chasm": "A deep crack in the earth",
  "Cackle": "To laugh in a loud harsh way",
  "Cavern": "A large cave",
  "Chaise": "A type of chair or carriage",
  "Chalet": "A wooden house in the mountains",
  "Camphor": "A strong-smelling substance used in medicine",
  "Caprice": "A sudden change of mood",
  "Carcass": "The dead body of an animal",
  "Caustic": "Able to burn or a harsh remark",
  "Charade": "A pretence or a word guessing game",
  "Chateau": "A large French country house",
  "Cleanse": "To clean thoroughly",
  "Commend": "To praise or recommend",
  "Connote": "To suggest an additional meaning",
  "Consign": "To deliver something to someone",
  "Contour": "An outline or shape",
  "Copious": "A large amount of something",
  "Cuisine": "A style of cooking",
  "Cemetery": "A place where people are buried",
  "Cohesion": "Sticking together as a group",
  "Comatose": "In a deep unconscious state",
  "Commuter": "A person who travels to work daily",
  "Conquest": "Winning control of something by force",
  "Contrary": "The opposite",
  "Culinary": "Related to cooking",
  "Cafeteria": "A self-service restaurant",
  "Capillary": "A very thin tube or blood vessel",
  "Caribbean": "Relating to the islands of the Caribbean Sea",
  "Catalogue": "A list of items available",
  "Catharsis": "A release of strong emotions",
  "Celestial": "Relating to the sky or heaven",
  "Chauffeur": "A person employed to drive a car",
  "Chronicle": "A record of events in order of time",
  "Clearance": "Permission or space to pass",
  "Cloakroom": "A room for coats and bags",
  "Coalition": "A group joined together for a purpose",
  "Colleague": "A person you work with",
  "Committee": "A group that makes decisions",
  "Commodity": "A product that can be bought and sold",
  "Continual": "Happening repeatedly",
  "Corrosion": "Gradual damage from chemicals",
  "Courteous": "Polite and respectful",
  "Capitalism": "An economic system based on private ownership",
  "Cautionary": "Serving as a warning",
  "Centrifuge": "A machine that spins to separate substances",
  "Countenance": "A person's face or expression",
  "Challenger": "A person who competes against another",
  "Chancellor": "A senior government or university official",
  "Chandelier": "A decorative light that hangs from the ceiling",
  "Charitable": "Generous and kind to others",
  "Chimpanzee": "A type of great ape",
  "Chronology": "The order events happen in time",
  "Classified": "Kept secret or arranged in groups",
  "Clandestiny": "Done in secret",
  "Colloquial": "Informal everyday language",
  "Combustion": "The process of burning",
  "Commentary": "A spoken or written explanation",
  "Comparable": "Similar enough to be compared",
  "Compassion": "A feeling of sympathy for others",
  "Concession": "Giving up something in an agreement",
  "Conference": "A formal meeting to discuss something",
  "Confidence": "Feeling sure about yourself",
  "Congestion": "Too much traffic or blocking",
  "Continuous": "Going on without stopping",
  "Contribute": "To give something to a common effort",
  "Controller": "A person or device that controls something",
  "Convincing": "Able to make you believe something",
  "Corruption": "Dishonest behaviour by those in power",
  "Ceremonious": "Following formal procedures",
  "Choreograph": "To design the steps of a dance",
  "Coefficient": "A number multiplied with a variable",
  "Corporation": "A large company",
  "Debut": "A first public appearance",
  "Depot": "A place for storing goods or vehicles",
  "Dahlia": "A garden flower with many petals",
  "Damsel": "A young woman",
  "Debris": "Scattered pieces of rubbish",
  "Detour": "An alternative route",
  "Deceive": "To make someone believe something false",
  "Devious": "Using tricks to get what you want",
  "Dilemma": "A difficult choice between two options",
  "Discern": "To recognise or understand something",
  "Dissent": "To disagree with an opinion",
  "Dossier": "A collection of documents about someone",
  "Draught": "A current of cool air",
  "Dropper": "A tube for measuring drops of liquid",
  "Drought": "A long period without rain",
  "Dubious": "Uncertain or possibly dishonest",
  "Dwindle": "To gradually become smaller",
  "Dynamic": "Full of energy and new ideas",
  "Deceased": "A person who has died",
  "Decipher": "To decode or work out the meaning",
  "Decisive": "Able to make decisions quickly",
  "Dementia": "A condition affecting memory",
  "Denounce": "To publicly declare something is wrong",
  "Derivate": "Something obtained from another source",
  "Designer": "A person who creates plans or styles",
  "Desolate": "Empty and lifeless",
  "Despotic": "Using power in a cruel way",
  "Detainee": "A person held in custody",
  "Detonate": "To cause a bomb to explode",
  "Diabetic": "A person with diabetes",
  "Diagnose": "To identify an illness",
  "Dialogue": "A conversation between people",
  "Dialysis": "A treatment to clean the blood",
  "Dictator": "A ruler with total power",
  "Disaster": "A sudden event causing great damage",
  "Dispense": "To give out supplies",
  "Doctrine": "A set of beliefs or principles",
  "Dolomite": "A type of rock or mineral",
  "Domicile": "A permanent home",
  "Dumbbell": "A weight used for exercise",
  "Dwelling": "A place where people live",
  "Dangerous": "Likely to cause harm",
  "Dentistry": "The work of a dentist",
  "Desiccate": "To dry out completely",
  "Desirable": "Worth having or wanting",
  "Desperate": "Having a great need or in a hopeless situation",
  "Detergent": "A cleaning substance",
  "Detriment": "Harm or damage",
  "Devaluate": "To reduce the value of something",
  "Deviation": "Moving away from what is normal",
  "Dexterity": "Skill in using your hands",
  "Disarming": "Making someone feel less worried",
  "Dishonour": "A loss of respect",
  "Dismantle": "To take apart piece by piece",
  "Diversity": "Having many different kinds",
  "Dysentery": "A severe stomach illness",
  "Dealership": "A business that sells products",
  "Definitely": "Without any doubt",
  "Deliberate": "Done on purpose",
  "Dependable": "Reliable and trustworthy",
  "Depression": "Feeling very sad for a long time",
  "Detachment": "Being emotionally distant",
  "Dictionary": "A book listing words and their meanings",
  "Disastrous": "Causing great damage",
  "Discourage": "To make someone less confident",
  "Dispensary": "A place where medicines are given out",
  "Distressed": "Feeling very upset",
  "Destination": "The place you are travelling to",
  "Disjunction": "A break or separation",
  "Disturbance": "Something that interrupts peace",
  "Easel": "A stand that holds a painting",
  "Efface": "To remove or make disappear",
  "Eucalyptus": "A tall Australian tree",
  "Embalm": "To preserve a body after death",
  "Embryo": "An unborn creature in early development",
  "Enmity": "Strong hatred between enemies",
  "Enwrap": "To cover or wrap around",
  "Eulogy": "A speech praising someone who has died",
  "Exceed": "To go beyond a limit",
  "Exhale": "To breathe out",
  "Ecstasy": "A feeling of great happiness",
  "Edifice": "A large impressive building",
  "Elegant": "Graceful and stylish",
  "Elusive": "Difficult to find or catch",
  "Emanate": "To come out from a source",
  "Embassy": "The office of an ambassador in another country",
  "Embroil": "To involve in a difficult situation",
  "Eminent": "Famous and respected",
  "Emulate": "To copy and try to do as well as someone",
  "Enthral": "To hold someone's attention completely",
  "Epitaph": "Words written on a gravestone",
  "Equator": "An imaginary line around the middle of Earth",
  "Equinox": "When day and night are equal length",
  "Erratic": "Not regular or predictable",
  "Essence": "The most important quality of something",
  "Eternal": "Lasting forever",
  "Evident": "Clearly seen or understood",
  "Excrete": "To pass waste from the body",
  "Exhaust": "To use up completely or make very tired",
  "Expanse": "A wide open area",
  "Easterly": "Coming from the east",
  "Effluent": "Liquid waste",
  "Effusive": "Showing too much enthusiasm",
  "Ejection": "Forcing something out",
  "Elliptic": "Oval shaped",
  "Elongate": "To make longer",
  "Embedded": "Fixed firmly inside something",
  "Embossed": "Having a raised design on the surface",
  "Emigrant": "A person who leaves their country",
  "Emissary": "A messenger sent on a mission",
  "Emission": "Something sent out like gas or light",
  "Emphasis": "Special importance given to something",
  "Energise": "To give energy to something",
  "Envisage": "To imagine something in the future",
  "Epilogue": "A section added at the end of a book",
  "Equation": "A mathematical statement with an equals sign",
  "Equipped": "Having what is needed",
  "Escapade": "An exciting or risky adventure",
  "Euphoria": "A feeling of extreme happiness",
  "Exempted": "Released from a rule or duty",
  "Exorcist": "A person who drives away evil spirits",
  "Exposure": "Being uncovered or made known",
  "Earnestly": "In a sincere and serious way",
  "Efficient": "Doing something well without wasting time",
  "Eliminate": "To completely remove",
  "Elucidate": "To explain clearly",
  "Embarrass": "To make someone feel awkward",
  "Emergency": "A sudden dangerous situation",
  "Enigmatic": "Mysterious and hard to understand",
  "Entrapped": "Caught in a trap",
  "Eradicate": "To completely destroy",
  "Escalator": "Moving stairs in a building",
  "Evolution": "The gradual development of living things",
  "Excessive": "Too much",
  "Exclusion": "Being left out",
  "Exploited": "Used unfairly for someone's benefit",
  "Explosion": "A sudden violent burst",
  "Egocentric": "Thinking only about yourself",
  "Elementary": "Simple and basic",
  "Employment": "Having a paid job",
  "Exhibition": "A public display of art or objects",
  "Experiment": "A test done to find out something",
  "Expression": "Showing feelings through words or face",
  "Extraction": "Removing something from somewhere",
  "Eligibility": "Meeting the requirements to do something",
  "Fawn": "A young deer or a light brown colour",
  "Feud": "A long argument between two groups",
  "Fauna": "The animals of a particular area",
  "Fiend": "A very cruel person or an evil being",
  "Folly": "A foolish act or decision",
  "Frond": "A large leaf of a fern or palm",
  "Frown": "To wrinkle your forehead when unhappy",
  "Fudge": "A soft sweet or to avoid answering clearly",
  "Fickle": "Changing opinions often",
  "Fiesta": "A festival or celebration",
  "Foemen": "Enemies in battle",
  "Foster": "To encourage growth or to care for a child",
  "Frisky": "Playful and full of energy",
  "Frolic": "To play in a lively way",
  "Furrow": "A long narrow cut in the ground",
  "Factual": "Based on facts",
  "Faculty": "A natural ability or department in a university",
  "Fancied": "Liked or imagined",
  "Fascist": "A person who believes in extreme control",
  "Fatigue": "Extreme tiredness",
  "Fibrous": "Made of or containing fibres",
  "Fidgety": "Unable to keep still",
  "Finesse": "Doing something with skill and care",
  "Fritter": "To waste time on small things",
  "Flaccid": "Soft and limp",
  "Flicker": "A small unsteady light or movement",
  "Foliage": "The leaves of a plant",
  "Forfeit": "To lose something as a penalty",
  "Forlorn": "Sad and alone",
  "Foundry": "A factory where metal is melted",
  "Fraught": "Filled with worry or problems",
  "Freaked": "Greatly shocked or scared",
  "Frizzle": "To fry with a sizzling sound",
  "Famished": "Extremely hungry",
  "Fastener": "A device that closes or joins things",
  "Feasible": "Possible to do",
  "Flourish": "To grow well or wave in the air",
  "Frenzied": "Wild and uncontrolled",
  "Fledgling": "A young bird learning to fly",
  "Freckled": "Having small brown spots on skin",
  "Fugitive": "A person running away from the law",
  "Fumigate": "To fill a place with gas to kill insects",
  "Fuselage": "The main body of an aircraft",
  "Fabricate": "To make up a story or manufacture something",
  "Ferocious": "Very fierce and violent",
  "Firmament": "The sky and heavens",
  "Fortunate": "Lucky",
  "Fragrance": "A pleasant smell",
  "Fraudster": "A person who tricks others for money",
  "Frivolous": "Not serious or important",
  "Fallacious": "Based on wrong ideas",
  "Fastidious": "Very careful about details",
  "Figurative": "Using words to represent something else",
  "Fraternity": "A group of people sharing common interests",
  "Fundraiser": "An event to collect money for a cause",
  "Fascination": "A strong interest in something",
  "Favouritism": "Treating some people better than others",
  "Feasibility": "Whether something is possible to do",
  "Financially": "Related to money matters",
  "Foreseeable": "Able to be predicted in the future",
  "Foreshorten": "To make something appear shorter",
  "Facilitation": "Making a process easier",
  "Fluorescence": "Giving off bright light",
  "Functionally": "In a way that works properly",
  "Gait": "The way a person or animal walks",
  "Gasp": "A sudden sharp intake of breath",
  "Gawk": "To stare in a rude way",
  "Ghat": "Steps leading down to a river",
  "Gnaw": "To bite or chew repeatedly",
  "Gout": "A painful joint condition",
  "Gaudy": "Too bright and showy",
  "Gauge": "A measuring instrument",
  "Gauze": "A thin transparent fabric",
  "Ghoul": "An evil spirit",
  "Gleam": "A small beam of light",
  "Gooey": "Sticky and soft",
  "Gaiety": "Cheerfulness and fun",
  "Ghetto": "A poor area of a city",
  "Grouse": "To complain or a type of bird",
  "Gypsum": "A mineral used in plaster",
  "Gyrate": "To move in circles",
  "Generic": "Not specific to one brand",
  "Genuine": "Real and not fake",
  "Ghastly": "Very unpleasant",
  "Giggler": "A person who giggles a lot",
  "Glimmer": "A faint light",
  "Globule": "A small round drop",
  "Gourmet": "High quality food",
  "Grapple": "To struggle with something",
  "Gravest": "Most serious",
  "Galleria": "A large shopping area",
  "Gamester": "A person who plays games",
  "Glorious": "Wonderful and magnificent",
  "Golliwog": "An old type of doll",
  "Gorgeous": "Very beautiful",
  "Graduate": "To complete a university degree",
  "Grammar": "The rules of a language",
  "Grandeur": "Great beauty and impressiveness",
  "Graphics": "Visual images and designs",
  "Graphite": "A soft carbon material used in pencils",
  "Gruesome": "Very unpleasant and shocking",
  "Guardian": "A person who protects or cares for another",
  "Guidance": "Advice and help",
  "Gullible": "Too easily tricked",
  "Generator": "A machine that produces electricity",
  "Gentility": "Polite and refined behaviour",
  "Geometric": "Relating to shapes and patterns",
  "Geriatric": "Relating to elderly people",
  "Gibberish": "Meaningless talk or words",
  "Giddiness": "A feeling of dizziness",
  "Glamorous": "Attractive and exciting",
  "Glorifies": "Praises and honours",
  "Goldsmith": "A person who makes gold objects",
  "Governess": "A woman employed to teach children",
  "Guarantee": "A promise that something will happen",
  "Guerrilla": "A fighter who uses surprise attacks",
  "Gymnasium": "A room for physical exercise",
  "Generality": "A statement that is broadly true",
  "Generosity": "The quality of being generous",
  "Gentrified": "Made more wealthy and fashionable",
  "Garnet": "A dark red precious stone",
  "Garrulous": "Talking too much",
  "Geographical": "Relating to the study of the Earth",
  "Grammalogue": "A word represented by a single symbol",
  "Guffaw": "A loud burst of laughter",
  "Guacamole": "A dip made from avocado",
  "Hack": "To cut roughly or to break into a computer",
  "Hurl": "To throw something with force",
  "Hymn": "A religious song",
  "Haul": "To pull or carry with effort",
  "Havoc": "Widespread destruction",
  "Hertz": "A unit measuring frequency",
  "Hoard": "A secret store of valuable things",
  "Holly": "A plant with red berries used at Christmas",
  "Hunch": "A feeling something is true without proof",
  "Hackle": "Hairs on an animal's neck that rise when angry",
  "Haggle": "To argue over a price",
  "Hamlet": "A very small village",
  "Hangar": "A large building for aircraft",
  "Hansom": "A type of horse-drawn carriage",
  "Hassel": "Trouble or annoyance",
  "Hatter": "A person who makes hats",
  "Hawker": "A person who sells goods in the street",
  "Header": "A heading or a header in football",
  "Herder": "A person who looks after animals",
  "Hernia": "When an organ pushes through muscle",
  "Hoarse": "A rough and croaky voice",
  "Hoaxer": "A person who tricks others",
  "Homage": "Showing respect to someone",
  "Halogen": "A type of element or light bulb",
  "Hammock": "A hanging bed made from netting",
  "Harness": "Straps used to control an animal",
  "Hatches": "Small doors or openings",
  "Haughty": "Acting superior to others",
  "Heathen": "A person with no religion",
  "Heinous": "Very wicked and evil",
  "Heliport": "A place where helicopters land",
  "Hideous": "Very ugly",
  "Hoarded": "Stored secretly",
  "Holster": "A holder for a gun",
  "Homonym": "A word with the same sound but different meaning",
  "Hormone": "A chemical in the body that controls functions",
  "Hostile": "Unfriendly and aggressive",
  "Hygiene": "Keeping yourself clean and healthy",
  "Hammered": "Hit with a hammer or exhausted",
  "Harasses": "Troubles or bothers someone repeatedly",
  "Hedgehog": "A small animal covered in spines",
  "Heritage": "Things passed down from past generations",
  "Hermetic": "Completely airtight",
  "Hesitant": "Slow to act because of uncertainty",
  "Hijacker": "A person who takes control of a vehicle",
  "Historic": "Important in history",
  "Homicide": "The killing of a person",
  "Humanity": "All human beings or kindness",
  "Humorous": "Funny and amusing",
  "Habituate": "To get used to something",
  "Hailstone": "A small ball of ice that falls from clouds",
  "Haphazard": "Done without a plan",
  "Hidebound": "Unwilling to change",
  "Hereditary": "Passed down through families",
  "Hierarchy": "A system of ranking from top to bottom",
  "Humdinger": "Something remarkably good",
  "Hindrance": "Something that makes progress difficult",
  "Horoscope": "A prediction based on star signs",
  "Hurricane": "A very powerful tropical storm",
  "Hydraulic": "Operated by the pressure of liquid",
  "Handicraft": "Something made by hand with skill",
  "Horrendous": "Extremely bad",
  "Hyphenated": "Joined with a hyphen",
  "Hallucinate": "To see things that are not really there",
  "Hospitality": "Being welcoming and generous to guests",
  "Habilitation": "The process of gaining skills",
  "Ibis": "A wading bird with a curved beak",
  "Icon": "A symbol or a famous person",
  "Irks": "Annoys or irritates",
  "Isle": "A small island",
  "Idiom": "A phrase with a meaning different from its words",
  "Imbed": "To fix firmly in something",
  "Impel": "To force or urge someone to do something",
  "Incur": "To cause something unpleasant to happen",
  "Inept": "Lacking skill or ability",
  "Ivory": "The white material from elephant tusks",
  "Impede": "To delay or prevent progress",
  "Impute": "To blame someone for something",
  "Incite": "To encourage someone to do something bad",
  "Ingest": "To swallow or absorb",
  "Intern": "A student working for experience",
  "Intuit": "To sense something without being told",
  "Irrupt": "To enter suddenly and forcefully",
  "Isomer": "A molecule with the same atoms in different order",
  "Imagery": "Vivid descriptions or pictures in your mind",
  "Immense": "Extremely large",
  "Impetus": "Something that causes things to happen",
  "Incisor": "A front cutting tooth",
  "Insight": "A deep understanding",
  "Interim": "A temporary period",
  "Irksome": "Annoying",
  "Isolate": "To separate from others",
  "Imperial": "Related to an empire",
  "Impostor": "A person pretending to be someone else",
  "Impunity": "Freedom from punishment",
  "Incisive": "Clear and direct",
  "Indulge": "To allow yourself something enjoyable",
  "Inhalant": "A substance breathed in",
  "Inherent": "A natural part of something",
  "Iniquity": "Immoral or unfair behaviour",
  "Innovate": "To create new ideas",
  "Insipid": "Lacking flavour or interest",
  "Integral": "Essential and necessary",
  "Incandescent": "Glowing with heat or very angry",
  "Intrigue": "A secret plan or to interest greatly",
  "Irritate": "To annoy someone",
  "Issuance": "The act of officially giving something out",
  "Ignorance": "Lack of knowledge",
  "Imaginary": "Existing only in the mind",
  "Impedance": "Resistance to the flow of electricity",
  "Implement": "To carry out a plan",
  "Impulsive": "Acting without thinking first",
  "Inaugural": "The first in a series",
  "Incessant": "Never stopping",
  "Increment": "A small regular increase",
  "Incurring": "Causing something negative to happen",
  "Intrinsic": "Being an essential part of something",
  "Invention": "Something newly created",
  "Isometric": "Having equal measurements",
  "Illuminist": "A person who seeks enlightenment",
  "Imprudence": "Lack of care and wisdom",
  "Inadequate": "Not enough or not good enough",
  "Influences": "Things that affect someone",
  "Ingredient": "A part used in making something",
  "Intolerant": "Not accepting differences in others",
  "Inkling": "A slight suspicion or idea",
  "Inculcation": "Teaching by repetition",
  "Inscrutable": "Impossible to understand",
  "Involuntary": "Done without meaning to",
  "Identifiable": "Able to be recognised",
  "Implementing": "Putting a plan into action",
  "Incidentally": "Happening by chance",
  "Indigestible": "Impossible or hard to digest",
  "Inflammation": "Redness and swelling in the body",
  "Interrogate": "To question someone intensely",
  "Jade": "A green precious stone",
  "Jinx": "Bad luck",
  "Joey": "A young kangaroo",
  "Jerky": "Moving in sudden sharp ways",
  "Jetty": "A structure built into water for boats",
  "Jaunty": "Cheerful and confident",
  "Jammed": "Stuck and unable to move",
  "Jerkin": "A close-fitting jacket",
  "Jester": "A person who entertained kings with jokes",
  "Jostle": "To push against others in a crowd",
  "Jovial": "Cheerful and friendly",
  "Jurist": "An expert in law",
  "Jacuzzi": "A large bath with jets of water",
  "Janitor": "A person who cleans a building",
  "Javelin": "A long spear thrown in athletics",
  "Jocular": "Fond of joking",
  "Jubilee": "A special anniversary celebration",
  "Jaundice": "A condition causing yellow skin",
  "Jeopardy": "Danger of loss or harm",
  "Juniper": "An evergreen plant with berries",
  "Judicial": "Relating to law and judges",
  "Julienne": "Cutting food into thin strips",
  "Juncture": "A particular point in time",
  "Juvenile": "Young or relating to young people",
  "Journalist": "A person who writes news",
  "Judgmental": "Too quick to criticise others",
  "Justifiable": "Having a good reason for something",
  "Knowledge": "Information and understanding",
  "Kindergarten": "A school for very young children",
  "Lager": "A light fizzy beer",
  "Lasso": "A rope with a loop for catching animals",
  "Leach": "To drain away gradually",
  "Leapt": "Past tense of leap",
  "Ledge": "A narrow shelf on a wall or cliff",
  "Lynch": "To kill someone without a legal trial",
  "Lackey": "A servant who does whatever is asked",
  "Lappet": "A small flap or fold",
  "Larder": "A cool room for storing food",
  "Larynx": "The voice box in your throat",
  "Laurel": "An evergreen plant used as a symbol",
  "Leaden": "Heavy and slow like lead",
  "League": "A group of teams or a distance measurement",
  "Limpid": "Clear and transparent",
  "Loathe": "To dislike intensely",
  "Loaves": "Plural of loaf of bread",
  "Looter": "A person who steals during a disaster",
  "Lunacy": "Behaviour that is wild and foolish",
  "Lurker": "A person who hides and watches secretly",
  "Lampoon": "To publicly mock someone",
  "Languor": "A pleasant tiredness",
  "Lanyard": "A cord worn around the neck for a badge",
  "Launder": "To wash clothes or to hide stolen money",
  "Leakage": "A slow escape of liquid or gas",
  "Legible": "Easy to read",
  "Leprosy": "A serious skin disease",
  "Laconic": "Using very few words",
  "Lounger": "A comfortable reclining chair",
  "Laudable": "Deserving praise",
  "Lavender": "A purple plant with a pleasant smell",
  "Lecturer": "A teacher at a university",
  "Lenience": "Being gentle and not strict",
  "Limerick": "A funny five-line poem",
  "Luncheon": "A formal lunch",
  "Lustrous": "Shining and glossy",
  "Lyricism": "An expressive quality in writing",
  "Laborious": "Needing a lot of hard work",
  "Lassitude": "Physical or mental tiredness",
  "Legendary": "Very famous",
  "Legislature": "A group that makes laws",
  "Leisurely": "Relaxed and unhurried",
  "Liability": "Being responsible for something",
  "Librarian": "A person who works in a library",
  "Lightning": "A flash of light in a storm",
  "Limousine": "A large luxurious car",
  "Longitude": "Distance measured east or west on a map",
  "Lubricant": "A substance used to reduce friction",
  "Luxurious": "Very comfortable and expensive",
  "Loneliness": "Feeling sad from being alone",
  "Launderette": "A place with coin-operated washing machines",
  "Mach": "A unit for measuring the speed of sound",
  "Minx": "A playful or cheeky girl",
  "Moan": "A low sound of pain or complaining",
  "Mince": "To cut into very small pieces",
  "Mourn": "To feel sadness after a loss",
  "Mulch": "Material spread on soil to protect plants",
  "Maggot": "A small worm-like creature",
  "Magpie": "A black and white bird",
  "Malice": "The desire to harm others",
  "Manger": "A container for animal food",
  "Mangle": "To damage something badly",
  "Martyr": "A person who suffers for a belief",
  "Meagre": "A very small amount",
  "Measly": "Very small and disappointing",
  "Menial": "Unimportant and boring work",
  "Mettle": "The ability to deal with difficulty",
  "Midget": "Something very small",
  "Moated": "Surrounded by a moat",
  "Morale": "The confidence of a group",
  "Morose": "Sad and bad-tempered",
  "Motley": "Made up of many different things",
  "Mucous": "Relating to the slimy fluid in the body",
  "Mussel": "A shellfish with a blue-black shell",
  "Mutiny": "A revolt against authority",
  "Muzzle": "The nose and mouth of an animal",
  "Myrtle": "An evergreen plant",
  "Maestro": "A great musician",
  "Magenta": "A bright pink-red colour",
  "Malaise": "A feeling of discomfort or illness",
  "Massive": "Very large",
  "Matinee": "An afternoon performance",
  "Melodic": "Having a pleasant tune",
  "Mileage": "The distance travelled in miles",
  "Mimicry": "Copying someone else's actions",
  "Mitosis": "Cell division",
  "Mongrel": "A dog of mixed breed",
  "Macaroon": "A sweet coconut or almond biscuit",
  "Mandarin": "A small orange or a Chinese language",
  "Manifesto": "A public declaration of beliefs",
  "Manually": "Done by hand",
  "Masculine": "Relating to men or male qualities",
  "Melamine": "A hard plastic material",
  "Memorize": "To learn something so you remember it",
  "Metaphor": "Describing something as if it is something else",
  "Misalign": "To position incorrectly",
  "Misquote": "To repeat something incorrectly",
  "Mortgage": "A loan to buy a house",
  "Murderer": "A person who kills someone",
  "Maelstrom": "A powerful whirlpool or chaotic situation",
  "Miscreant": "A person who does wrong",
  "Malleable": "Easy to shape or influence",
  "Mandatory": "Required by law or rules",
  "Medallion": "A large medal worn as jewellery",
  "Momentary": "Lasting only a moment",
  "Mercantile": "Relating to trade",
  "Meticulous": "Very careful and precise",
  "Mysterious": "Strange and hard to explain",
  "Magnificent": "Very impressive and beautiful",
  "Maintenance": "Keeping something in good condition",
  "Microscopic": "Too small to see without a microscope",
  "Mischievous": "Causing trouble in a playful way",
  "Mountaineer": "A person who climbs mountains",
  "Materialistic": "Caring too much about possessions",
  "Nape": "The back of the neck",
  "Neon": "A gas used in bright signs",
  "Newt": "A small amphibian",
  "Numb": "Unable to feel anything",
  "Nettle": "A plant with stinging leaves",
  "Noose": "A loop that tightens when pulled",
  "Notch": "A small cut or mark",
  "Nudge": "A gentle push",
  "Nymph": "A nature spirit or young insect",
  "Naught": "Nothing or zero",
  "Nectar": "A sweet liquid in flowers",
  "Nephew": "The son of your brother or sister",
  "Neuron": "A nerve cell in the brain",
  "Newest": "Most recent",
  "Nicety": "A fine detail or polite behaviour",
  "Niggle": "A small worry",
  "Nobble": "To prevent something by cheating",
  "Notary": "A person who witnesses legal documents",
  "Notion": "An idea or belief",
  "Naivete": "Lack of experience or wisdom",
  "Narrate": "To tell a story",
  "Naughty": "Behaving badly",
  "Nestled": "Settled comfortably",
  "Nickel": "A metal or a five-cent coin",
  "Nitrate": "A chemical compound used in fertilisers",
  "Nominee": "A person put forward for an award",
  "Nullify": "To make something invalid",
  "Narcotic": "A drug that dulls the senses",
  "Nauseate": "To make someone feel sick",
  "Nautical": "Relating to ships and the sea",
  "Noisiest": "Making the most noise",
  "Nostalgia": "A longing for the past",
  "Nourished": "Provided with healthy food",
  "Novelist": "A person who writes novels",
  "Nuisance": "Something that causes annoyance",
  "Numeracy": "The ability to work with numbers",
  "Numerous": "Many",
  "Nurturing": "Caring for and encouraging growth",
  "Necessity": "Something that is absolutely needed",
  "Nectarine": "A smooth-skinned peach",
  "Notorious": "Famous for something bad",
  "Nullifies": "Makes something have no effect",
  "Negligency": "Failure to take proper care",
  "Negotiable": "Open to discussion and agreement",
  "Netiquette": "Rules for polite behaviour online",
  "Noticeable": "Easy to see or notice",
  "Numeration": "The process of counting",
  "Nonetheless": "In spite of that",
  "Ogre": "A large frightening creature in stories",
  "Okra": "A green vegetable",
  "Omen": "A sign of what will happen in the future",
  "Obese": "Very overweight",
  "Ochre": "A yellow-brown colour",
  "Octet": "A group of eight",
  "Oblate": "Flattened at the poles",
  "Oblige": "To do a favour for someone",
  "Obtuse": "Not sharp or slow to understand",
  "Ocular": "Relating to the eye",
  "Opaque": "Not able to be seen through",
  "Orator": "A skilled public speaker",
  "Obscene": "Offensive and shocking",
  "Obscure": "Not well known or hard to understand",
  "Obtrude": "To push something unwanted on others",
  "Offense": "Something that breaks a law or upsets people",
  "Offhand": "Without much thought or care",
  "Offside": "In a position not allowed in a sport",
  "Omnibus": "A book with many works or a bus",
  "Opposed": "Against something",
  "Optimum": "The best possible",
  "Oratory": "The skill of public speaking",
  "Obstacle": "Something that blocks your way",
  "Obstruct": "To block or hinder",
  "Omission": "Something that has been left out",
  "Operable": "Able to work",
  "Ordinary": "Normal and usual",
  "Organism": "A living thing",
  "Obligated": "Required to do something",
  "Occupancy": "Using or living in a space",
  "Occurring": "Happening",
  "Opportune": "Happening at the right time",
  "Oppressor": "A person who uses power cruelly",
  "Oscillate": "To swing back and forth",
  "Observant": "Quick to notice things",
  "Obtrusion": "Forcing yourself where unwanted",
  "Orphanage": "A home for children without parents",
  "Overhyped": "Promoted more than deserved",
  "Obediently": "In a way that follows instructions",
  "Observance": "Following a custom or rule",
  "Occurrence": "Something that happens",
  "Oesophagus": "The tube from the throat to the stomach",
  "Optimistic": "Expecting good things to happen",
  "Organically": "In a natural way",
  "Occasionally": "Sometimes but not often",
  "Palsy": "A condition causing shaking",
  "Pansy": "A small colourful garden flower",
  "Parch": "To make very dry",
  "Penne": "A type of tube-shaped pasta",
  "Peril": "Serious danger",
  "Pixel": "A tiny dot that makes up an image on screen",
  "Plank": "A long flat piece of wood",
  "Pleat": "A fold in fabric",
  "Prior": "Coming before in time",
  "Proxy": "A person acting for another",
  "Prune": "To cut back a plant or a dried plum",
  "Puree": "Food crushed into a smooth paste",
  "Pygmy": "Something very small",
  "Pylon": "A tall tower that carries electricity cables",
  "Pallor": "An unhealthy pale colour",
  "Parity": "Being equal",
  "Pastry": "A baked dough used in pies",
  "Patchy": "Not even or consistent",
  "Peruse": "To read carefully",
  "Pestle": "A tool for crushing things",
  "Pewter": "A grey metal used for making dishes",
  "Pharos": "An ancient lighthouse",
  "Pilfer": "To steal small things",
  "Plaque": "A flat sign or a deposit on teeth",
  "Pliant": "Easily bent or influenced",
  "Podium": "A raised platform to stand on",
  "Prance": "To walk with high steps",
  "Propel": "To push something forward",
  "Pseudo": "Pretending to be something",
  "Pumice": "A light rock used to smooth skin",
  "Punter": "A person who bets or a customer",
  "Purist": "A person who follows rules strictly",
  "Purser": "A ship's officer in charge of accounts",
  "Palette": "A board for mixing paint colours",
  "Palmist": "A person who reads palms",
  "Palpate": "To examine by touch",
  "Panacea": "A cure for all problems",
  "Parsley": "A herb used in cooking",
  "Peevish": "Easily irritated",
  "Pensive": "Deep in thought",
  "Perjury": "Lying under oath in court",
  "Perplex": "To confuse someone greatly",
  "Petrify": "To frighten greatly or turn to stone",
  "Pianist": "A person who plays piano",
  "Pillion": "A seat behind the driver on a motorbike",
  "Placebo": "A fake medicine",
  "Pledged": "Made a solemn promise",
  "Pliable": "Easy to bend or influence",
  "Plugged": "Blocked or connected",
  "Pompous": "Too proud of yourself",
  "Portray": "To show or describe",
  "Poultry": "Chickens and other farm birds",
  "Prattle": "To talk for a long time about nothing",
  "Profess": "To claim or declare something",
  "Psychic": "Having the ability to sense the future",
  "Purport": "To appear or claim to be",
  "Pursuit": "Chasing after something",
  "Palatial": "Grand like a palace",
  "Palisade": "A fence of wooden stakes",
  "Palpable": "So strong it can almost be felt",
  "Pamphlet": "A small booklet with information",
  "Paraffin": "A waxy or oily fuel substance",
  "Partisan": "A strong supporter of a group",
  "Pedigree": "The record of an animal's ancestors",
  "Petition": "A request signed by many people",
  "Pheasant": "A large colourful wild bird",
  "Pinnacle": "The highest point",
  "Pleasure": "A feeling of happiness",
  "Plethora": "A very large amount",
  "Polluter": "Something that causes pollution",
  "Populous": "Having many people",
  "Premiere": "The first performance of something",
  "Pristine": "Perfectly clean and new",
  "Prologue": "An introduction to a story",
  "Prompter": "A person who reminds actors of lines",
  "Prospect": "The possibility of something happening",
  "Prostate": "A gland in the male body",
  "Province": "A region of a country",
  "Prudence": "Being careful and wise",
  "Publican": "A person who runs a pub",
  "Paralysed": "Unable to move",
  "Partially": "Not completely",
  "Patriotic": "Showing love for your country",
  "Perforate": "To make holes in something",
  "Periphery": "The outer edge of something",
  "Permanent": "Lasting forever",
  "Permitted": "Allowed",
  "Pollutant": "A substance that causes pollution",
  "Ponderous": "Very heavy or slow",
  "Possessed": "Controlled by something or owned",
  "Precisely": "Exactly and accurately",
  "Preferred": "Liked more than others",
  "Prevalent": "Common and widespread",
  "Privilege": "A special right given to some people",
  "Processor": "A device that handles data",
  "Prominent": "Important and well known",
  "Prosecute": "To take legal action against someone",
  "Punctuate": "To add punctuation to writing",
  "Pedestrian": "A person walking",
  "Peninsular": "A piece of land nearly surrounded by water",
  "Perception": "The way you understand something",
  "Presidency": "The role of being president",
  "Quaff": "To drink quickly and enthusiastically",
  "Query": "A question",
  "Quirk": "An unusual habit",
  "Queasy": "Feeling slightly sick",
  "Queues": "Lines of people waiting",
  "Qualify": "To meet requirements",
  "Quality": "How good something is",
  "Quantum": "A very small amount of energy",
  "Quieten": "To make less noisy",
  "Quantity": "How much of something there is",
  "Quibbler": "A person who argues about small things",
  "Quietest": "Making the least noise",
  "Quotable": "Worth repeating or quoting",
  "Qualities": "Features or characteristics",
  "Quickened": "Became faster",
  "Radii": "Plural of radius",
  "Rebut": "To prove something is wrong",
  "Reign": "To rule as a king or queen",
  "Resin": "A sticky substance from trees",
  "Retch": "To feel like vomiting",
  "Roach": "A type of fish or a cockroach",
  "Rouge": "A red powder used as make-up",
  "Route": "A path from one place to another",
  "Ruddy": "Having a healthy red colour",
  "Rusty": "Covered with rust",
  "Racism": "Treating people unfairly because of race",
  "Radial": "Going outward from a centre point",
  "Ramble": "To walk for pleasure or to talk without focus",
  "Rather": "To a certain degree or preferably",
  "Rebate": "A refund of part of a payment",
  "Rebuke": "To tell someone off firmly",
  "Recess": "A break from work or a small space in a wall",
  "Redeem": "To save or exchange for something",
  "Regime": "A system of government",
  "Relish": "To enjoy greatly or a condiment",
  "Repine": "To feel unhappy about something",
  "Repose": "Rest and relaxation",
  "Revere": "To respect deeply",
  "Review": "To look at again or a written opinion",
  "Ripped": "Torn apart",
  "Router": "A device that connects to the internet",
  "Rudder": "A device for steering a boat",
  "Radiate": "To send out light or heat",
  "Ragging": "Teasing someone",
  "Ramming": "Pushing with great force",
  "Rampage": "A period of violent behaviour",
  "Ranches": "Large farms for animals",
  "Rapport": "A friendly understanding with someone",
  "Raucous": "Loud and rough",
  "Reagent": "A substance used in a chemical reaction",
  "Realism": "Seeing things as they really are",
  "Recruit": "To find new members",
  "Refinery": "A place where oil is processed",
  "Reformer": "A person who makes improvements",
  "Regimen": "A set plan for health",
  "Remorse": "Feeling sorry for doing wrong",
  "Replete": "Very full",
  "Residue": "What remains after something is used",
  "Respite": "A short break from difficulty",
  "Retting": "Soaking fibre to soften it",
  "Revenge": "Harming someone who harmed you",
  "Revenue": "Money earned by a business",
  "Ricotta": "A soft Italian cheese",
  "Rippled": "Had small waves",
  "Rivalry": "Competition between two people",
  "Roaster": "A pan for roasting food",
  "Rockery": "A garden of rocks and plants",
  "Rookery": "A place where birds nest in groups",
  "Roughen": "To make rough",
  "Royalty": "Members of a royal family",
  "Rubbish": "Waste material or nonsense",
  "Ruinous": "Causing great damage",
  "Rummage": "To search through things",
  "Rupture": "A sudden break",
  "Ravenous": "Extremely hungry",
  "Reactant": "A substance that takes part in a reaction",
  "Reassign": "To give a different role",
  "Reckoned": "Believed or calculated",
  "Redeemer": "A person who saves others",
  "Referred": "Directed to someone for help",
  "Relevant": "Connected to what is being discussed",
  "Remedial": "Intended to improve a difficulty",
  "Reminded": "Made to remember something",
  "Repellent": "Something that drives away insects",
  "Reproach": "To express disapproval",
  "Resident": "A person living in a place",
  "Resonate": "To have a strong effect",
  "Resource": "Something available to be used",
  "Restrain": "To hold back",
  "Restrict": "To limit something",
  "Retainer": "A device or a fee paid to keep someone",
  "Retrieve": "To get something back",
  "Revealed": "Made known",
  "Reversal": "A change to the opposite",
  "Rhetoric": "The skill of persuasive speaking",
  "Ridicule": "To make fun of someone",
  "Rigorous": "Very thorough and careful",
  "Roadster": "A type of open car",
  "Roentgen": "A unit for measuring radiation",
  "Roughage": "Fibre in food",
  "Rucksack": "A bag worn on your back",
  "Ruminant": "An animal that chews the cud",
  "Ravishing": "Very beautiful",
  "Rebellion": "A fight against authority",
  "Recession": "A period when the economy slows down",
  "Recommend": "To suggest as a good choice",
  "Rehearsal": "Practice before a performance",
  "Remainder": "What is left over",
  "Rustiness": "The state of being rusty",
  "Respondent": "A person who answers",
  "Rollicking": "Lively and entertaining",
  "Reallocated": "Distributed again differently",
  "Recognition": "Knowing who someone is",
  "Sable": "Black or a small animal",
  "Sabre": "A curved sword",
  "Sauna": "A room filled with steam for relaxation",
  "Shoal": "A group of fish or shallow water",
  "Sieve": "A tool with holes for straining",
  "Sinew": "A tough cord that joins muscle to bone",
  "Slain": "Past tense of slay",
  "Smirk": "A self-satisfied smile",
  "Smoky": "Filled with smoke",
  "Snaky": "Like a snake or twisting",
  "Spawn": "Eggs of fish or frogs",
  "Sacred": "Holy and respected",
  "Saddle": "A seat on a horse or bicycle",
  "Scanty": "Very small or not enough",
  "Scurry": "To move quickly with small steps",
  "Seethe": "To be very angry",
  "Seized": "Taken by force",
  "Sequel": "A story that follows another",
  "Sewage": "Waste water from buildings",
  "Sheath": "A cover for a blade",
  "Shovel": "A tool for digging",
  "Shrewd": "Clever at understanding",
  "Shroud": "A cloth covering a dead body",
  "Signet": "A small seal used to mark documents",
  "Silver": "A shiny white metal",
  "Simmer": "To cook gently just below boiling",
  "Simper": "To smile in a silly way",
  "Skimpy": "Too small or not enough",
  "Sleazy": "Dishonest and unpleasant",
  "Sludge": "Thick muddy material",
  "Solemn": "Serious and dignified",
  "Sparse": "Thin and spread out",
  "Splint": "A rigid support for a broken bone",
  "Squash": "To flatten or a sport or a drink",
  "Squire": "A young man serving a knight",
  "Starry": "Full of stars",
  "Subtle": "Not obvious",
  "Suburb": "A residential area outside a city",
  "Summon": "To officially call someone",
  "Saddles": "Seats on horses or bicycles",
  "Sagging": "Hanging down loosely",
  "Satiate": "To fully satisfy hunger",
  "Savoury": "Having a salty flavour",
  "Scalpel": "A small sharp knife used in surgery",
  "Scenery": "The natural features of a landscape",
  "Scriber": "A pointed tool for marking",
  "Scuffle": "A short confused fight",
  "Seepage": "Liquid slowly leaking through",
  "Sheriff": "A law officer",
  "Shrivel": "To become dry and wrinkled",
  "Smasher": "Something very impressive",
  "Snippet": "A small piece of information",
  "Snooker": "A billiard ball game",
  "Snorkel": "A tube for breathing underwater",
  "Splashy": "Making big splashes",
  "Spoiler": "Something that reveals an ending",
  "Squalid": "Very dirty and unpleasant",
  "Stagger": "To walk unsteadily",
  "Staunch": "Very loyal and committed",
  "Steroid": "A chemical substance in medicine",
  "Subsist": "To manage to survive",
  "Subvert": "To undermine or destroy",
  "Succeed": "To achieve what you wanted",
  "Succumb": "To give in to something",
  "Suction": "A force that pulls things inward",
  "Salinity": "The amount of salt in water",
  "Sanctity": "Holiness and importance",
  "Sapphire": "A blue precious stone",
  "Sculptor": "A person who makes sculptures",
  "Sensible": "Showing good judgement",
  "Sergeant": "A military or police rank",
  "Shepherd": "A person who looks after sheep",
  "Simulate": "To imitate something",
  "Sinister": "Suggesting evil",
  "Skeletal": "Relating to the skeleton",
  "Smoothie": "A blended fruit drink",
  "Smuggler": "A person who moves goods illegally",
  "Solidify": "To become solid",
  "Solitary": "Being alone",
  "Solstice": "When the sun is farthest from the equator",
  "Souvenir": "An object kept as a memory",
  "Spacious": "Having a lot of space",
  "Spinster": "An older unmarried woman",
  "Spirited": "Full of energy and enthusiasm",
  "Splinter": "A small sharp piece broken off",
  "Splutter": "To make spitting sounds",
  "Sterling": "British currency or excellent quality",
  "Symbolic": "Standing for something else",
  "Secretary": "A person who does office work",
  "Sedentary": "Spending a lot of time sitting",
  "Segregate": "To separate groups of people",
  "Simpleton": "A person lacking intelligence",
  "Southerly": "Coming from the south",
  "Sovereign": "A ruler or a gold coin",
  "Spaghetti": "Long thin pasta",
  "Spellbind": "To hold someone's complete attention",
  "Structure": "The way something is built",
  "Scholastic": "Relating to school",
  "Skyscraper": "A very tall building",
  "Supplement": "Something added to improve",
  "Spontaneous": "Happening without planning",
  "Statistical": "Relating to statistics",
  "Thrum": "A continuous humming sound",
  "Twine": "Strong thread or string",
  "Tabbed": "Having tabs",
  "Talcum": "A soft white powder",
  "Tannin": "A substance found in tea",
  "Tassel": "A bunch of hanging threads",
  "Tattoo": "A design on skin or a military display",
  "Thrash": "To beat or to move wildly",
  "Thwart": "To prevent someone succeeding",
  "Timbre": "The quality of a musical sound",
  "Toucan": "A tropical bird with a large beak",
  "Trowel": "A small tool for spreading plaster",
  "Trudge": "To walk slowly and heavily",
  "Turret": "A small tower on a building",
  "Twirly": "Spinning in circles",
  "Typify": "To be a typical example of",
  "Tyrant": "A cruel ruler",
  "Tabloid": "A small newspaper",
  "Tantrum": "A sudden burst of anger",
  "Tarnish": "To make dull or damage reputation",
  "Tedious": "Long and boring",
  "Tempted": "Wanting to do something you should not",
  "Textual": "Relating to text",
  "Theorem": "A mathematical statement to be proved",
  "Thyroid": "A gland in the neck",
  "Titular": "Holding a title",
  "Tonsure": "A shaved patch on a monk's head",
  "Tornado": "A violent spinning wind",
  "Traitor": "A person who betrays others",
  "Tribune": "A platform for speaking",
  "Trouser": "A garment covering the legs",
  "Truckie": "An informal word for a truck driver",
  "Twaddle": "Silly meaningless talk",
  "Talisman": "An object believed to bring luck",
  "Tapestry": "A heavy woven picture",
  "Terminus": "The end of a bus or train line",
  "Thatched": "Covered with a straw roof",
  "Threaten": "To warn of harm",
  "Timidity": "Being shy and fearful",
  "Tranquil": "Calm and peaceful",
  "Trapezia": "Plural of trapezium",
  "Treasury": "A place where money is kept",
  "Tweezers": "A small tool for picking things up",
  "Twitcher": "A person who watches birds",
  "Tantalize": "To tease by showing something desirable",
  "Taxidermy": "Preparing and stuffing dead animals",
  "Technique": "A particular way of doing something",
  "Telescopic": "Relating to a telescope",
  "Temperate": "Mild and not extreme",
  "Terminate": "To bring to an end",
  "Territory": "An area belonging to someone",
  "Therapist": "A person who helps with mental health",
  "Thesaurus": "A book of words with similar meanings",
  "Throbbing": "Beating with a strong pulse",
  "Tolerable": "Acceptable but not great",
  "Transcend": "To go beyond normal limits",
  "Transistor": "A device that controls electricity",
  "Transitive": "A verb that needs an object",
  "Transpire": "To happen or become known",
  "Travelled": "Moved from place to place",
  "Treachery": "Betrayal of trust",
  "Trialogue": "A conversation between three people",
  "Tubercular": "Relating to tuberculosis",
  "Terminator": "Something that ends or destroys",
  "Terracotta": "A reddish-brown earthenware material",
  "Theatrical": "Relating to theatre",
  "Trafficker": "A person who trades illegally",
  "Translator": "A person who converts one language to another",
  "Tentatively": "In an uncertain way",
  "Thriftiness": "Being careful with money",
  "Transparent": "Able to be seen through",
  "Udder": "The bag-like organ of a cow that gives milk",
  "Urban": "Relating to a city",
  "Usher": "A person who guides people to their seats",
  "Unison": "All doing the same thing together",
  "Unveil": "To reveal something new",
  "Unwary": "Not paying attention to danger",
  "Unwind": "To relax or to undo something coiled",
  "Unwrap": "To remove the wrapping from something",
  "Uproar": "A loud noisy situation",
  "Urchin": "A poor ragged child or a sea creature",
  "Unified": "Joined together as one",
  "Unlatch": "To open a latch",
  "Upraise": "To lift up",
  "Urgency": "The need to act quickly",
  "Usually": "Most of the time",
  "Utterly": "Completely",
  "Ugliness": "Being unpleasant to look at",
  "Unmanned": "Without a human crew",
  "Ulcerated": "Having painful sores",
  "Umbilical": "Relating to the navel",
  "Unanimous": "Everyone agreeing",
  "Unflapped": "Not worried or confused",
  "Ultrasound": "Sound waves used to see inside the body",
  "Unconscious": "Not awake or aware",
  "Utilitarian": "Designed to be useful rather than beautiful",
  "Vain": "Too proud of yourself or having no effect",
  "Veal": "Meat from a young calf",
  "Veil": "A thin covering over the face",
  "Vague": "Not clear or definite",
  "Valet": "A person who parks cars or a servant",
  "Viola": "A stringed instrument larger than a violin",
  "Veneer": "A thin layer covering something",
  "Viewer": "A person who watches something",
  "Vigour": "Physical strength and energy",
  "Valiant": "Showing courage",
  "Vaulted": "Jumped over or having an arched ceiling",
  "Venison": "Meat from a deer",
  "Verdict": "A decision made in court",
  "Vertigo": "A feeling of dizziness",
  "Vicious": "Deliberately cruel",
  "Vintage": "Something from the past that is high quality",
  "Viscous": "Thick and sticky",
  "Voucher": "A piece of paper that can be exchanged",
  "Vagabond": "A person who wanders without a home",
  "Vanquish": "To defeat completely",
  "Venomous": "Producing poison",
  "Veracity": "Telling the truth",
  "Verbatim": "Exactly word for word",
  "Vertebra": "A bone in the spine",
  "Vibrator": "A device that vibrates",
  "Vigilant": "Watching carefully for danger",
  "Virtuous": "Having good moral qualities",
  "Vivacity": "Being lively and spirited",
  "Vocation": "A job that suits you perfectly",
  "Vibration": "A rapid shaking movement",
  "Vigilance": "Careful watchfulness",
  "Vindicate": "To prove someone was right",
  "Vehemently": "With strong feeling",
  "Wade": "To walk through water",
  "Waft": "To move gently through the air",
  "Wage": "Money earned for work",
  "Wane": "To gradually decrease",
  "Wick": "The string in a candle",
  "Wacky": "Funny and unusual",
  "Wager": "A bet",
  "Waive": "To give up a right",
  "Waltz": "A formal dance or to move confidently",
  "Weary": "Very tired",
  "Wedge": "A triangular piece used to hold things",
  "Weird": "Strange and unusual",
  "Whiff": "A slight smell",
  "Whisk": "To mix quickly or move fast",
  "Whorl": "A spiral pattern",
  "Wield": "To hold and use a weapon",
  "Wrath": "Great anger",
  "Wring": "To twist tightly",
  "Waddle": "To walk with short steps side to side",
  "Waiver": "An agreement to give up a right",
  "Wangle": "To obtain by clever means",
  "Wanton": "Deliberate cruelty without reason",
  "Wholly": "Completely",
  "Wiggle": "To move with small side to side movements",
  "Wither": "To dry up and shrink",
  "Wombat": "A small Australian burrowing animal",
  "Wonder": "A feeling of amazement",
  "Worsen": "To become worse",
  "Wraith": "A ghost",
  "Wreath": "A ring of flowers or leaves",
  "Wrench": "To twist violently or a tool",
  "Wrestle": "To fight by grappling",
  "Wretch": "An unfortunate person",
  "Warrant": "An official document or justification",
  "Weighty": "Heavy or important",
  "Whisper": "To speak very quietly",
  "Worsted": "A type of wool fabric",
  "Wounded": "Hurt or injured",
  "Wriggle": "To twist and turn",
  "Wrangler": "A person who looks after horses",
  "Wallowing": "Rolling in mud or feeling self-pity",
  "Weekender": "Someone who does something at weekends",
  "Westerner": "A person from the western part of a country",
  "Worthiest": "Most deserving",
  "Withdrawal": "Taking something back or leaving",
  "Waterlogged": "Completely soaked with water",
  "Whereabout": "The place where someone is",
  "Wheelbarrow": "A small cart pushed by hand",
  "Xylem": "The part of a plant that carries water",
  "Xanthium": "A plant with spiny seeds",
  "Xerophytes": "Plants that survive in dry conditions",
  "Yelp": "A sharp cry of pain",
  "Yore": "A long time ago",
  "Yowl": "A loud cry of pain",
  "Yearn": "To want something very much",
  "Yield": "To produce or to give way",
  "Yokel": "A simple person from the countryside",
  "Yelled": "Shouted loudly",
  "Yeoman": "A farmer who owns land",
  "Youngster": "A young person",
  "Zany": "Amusingly unusual",
  "Zonk": "To hit hard or fall asleep suddenly",
  "Zesty": "Having a strong lively flavour",
  "Zealot": "A person who is extremely passionate",
  "Zipper": "A fastening device with teeth",
  "Zither": "A stringed musical instrument",
  "Zounds": "An old exclamation of surprise",
  "Zoology": "The study of animals",
  "Zookeeper": "A person who looks after animals in a zoo",
};

// Case-insensitive lookup (built lazily) so a word's casing never matters.
let lowerIndex: Record<string, string> | null = null;

export function getMeaning(word: string): string | undefined {
  if (WORD_MEANINGS[word]) return WORD_MEANINGS[word];
  if (!lowerIndex) {
    lowerIndex = {};
    for (const key of Object.keys(WORD_MEANINGS)) {
      lowerIndex[key.toLowerCase()] = WORD_MEANINGS[key];
    }
  }
  return lowerIndex[word.toLowerCase()];
}
